name: hello world
on: [push]
jobs:
  default-job:
    runs-on:
      - codebuild-test-codebuild-runner-reserved-fleet-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:test-action-runner-default
    steps:
      - name: runner setup
        run: .github/scripts/runner_setup.sh
      - name: checkout github code
        uses: actions/checkout@v4
      - name: check github files
        shell: bash
        run: |
          cat README.md
  x86-cpu-job:
    runs-on:
      - codebuild-test-codebuild-runner-reserved-fleet-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:test-action-runner-x86-cpu
    steps:
      - name: runner setup
        run: .github/scripts/runner_setup.sh
      - name: checkout github code
        uses: actions/checkout@v4
      - name: check github files
        shell: bash
        run: |
          cat README.md
  x86-single-gpu-job:
    runs-on:
      - codebuild-test-codebuild-runner-reserved-fleet-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:test-action-runner-x86-single-gpu
    steps:
      - name: runner setup
        run: .github/scripts/runner_setup.sh && nvidia-smi
      - name: checkout github code
        uses: actions/checkout@v4
      - name: check github files
        shell: bash
        run: |
          cat README.md
    