name: hello world
on: [push]
jobs:
  hello-world-job:
    runs-on:
      - codebuild-test-codebuild-runner-reserved-fleet-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "hello world"
