name: hello world
on: [push]
jobs:
  hello-world-job:
    runs-on:
      - codebuild-test-codebuild-runner-reserved-fleet-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: cat /etc/motd
      - run: nvidia-smi
      - run: echo "Workspace path ${{ github.workspace }}"
      - run: cat ${{ github.workspace }}/the_cicd_dance.txt