name: hello world
on: [push]
jobs:
  hello-world-job:
    runs-on:
      - codebuild-test-codebuild-runner-reserved-fleet-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: check DLAMI stuff
        shell: bash
        run: |
          cat /etc/motd
          nvidia-smi
      - nane: checkout github code
        uses: actions/checkout@v4
      - name: check github files
        shell: bash
        run: |
          ls -al
          cat README.md