name: hello world
on: [push]
jobs:
  default-job:
    runs-on:
      - codebuild-test-codebuild-runner-reserved-fleet-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:test-action-runner-default
    steps:
      - name: check DLAMI stuff
        shell: bash
        run: |
          cat /etc/motd
          docker --version
          python3 --version
          python3 -m pip install uv 
      - name: checkout github code
        uses: actions/checkout@v4
      - name: check github files
        shell: bash
        run: |
          cat README.md
  x86-cpu-job:
    runs-on:
      - codebuild-test-codebuild-runner-reserved-fleet-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:test-action-runner-x86-cpu
    steps:
      - name: check DLAMI stuff
        shell: bash
        run: |
          cat /etc/motd
          docker --version
          python3 --version
          python3 -m pip install uv 
      - name: checkout github code
        uses: actions/checkout@v4
      - name: check github files
        shell: bash
        run: |
          cat README.md
  x86-single-gpu-job:
    runs-on:
      - codebuild-test-codebuild-runner-reserved-fleet-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:test-action-runner-x86-single-gpu
    steps:
      - name: check DLAMI stuff
        shell: bash
        run: |
          cat /etc/motd
          docker --version
          python3 --version
          python3 -m pip install uv 
          nvidia-smi
      - name: checkout github code
        uses: actions/checkout@v4
      - name: check github files
        shell: bash
        run: |
          cat README.md
    