name: run nvidia-smi
on: [push]
jobs:
  run-nvidia-smi:
    runs-on:
      - codebuild-test-codebuild-runner-reserved-fleet-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: nvidia-smi
